config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to @article
    else
      render 'new'
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
  <div class="container">
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
          <% @article.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @article, local: true) do |form| %>
        <div class="form-group row">
          <%= form.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= form.text_field :title, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= form.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= form.text_area :description, rows: 10, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row mt-4 justify-content-center">
          <%= form.submit class: "btn btn-outline-light btn-lg col-2" %>
        </div>
      <% end %>
      <div class="form-group row justify-content-center">
        <%= link_to 'Cancel and return to articles listing', articles_path %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Create New Article</h1>

  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div id="page-content">
  <p id="notice"><%= notice %></p>

  <h1 class="text-center mt-4">Listing all Articles</h1>

  <div class="container">
    <% @articles.each do |article| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header fst-italic">
              by Robert Wadsworth
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
              <p class="card-text"><%= truncate(article.description, length: 100) %></p>
              <%= link_to "View", article_path(article), class: "btn btn-outline-success text-success" %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info text-info" %>
              <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger text-danger" %>
            </div>
            <div class="card-footer text-muted">
              <small>created <%= time_ago_in_words(article.created_at) %> ago,
              edited <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div id="page-content">
  <p id="notice"><%= notice %></p>
  <h1 class="text-center mt-4">Create New Article</h1>
  
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<h1>Showing Article Details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<%= link_to 'Edit', edit_article_path(@article) %> | 
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %> | 
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">AlphaBlog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <p class="lead">
        <a class="btn btn-success btn-lg text-white" href="#" role="button">Learn more</a>
      </p>
    </div>
  </div>
</div>

<footer class="footer mt-auto py-3 bg-dark">
  <div class="container text-center">
    <span class="text-muted text-black">
      Copyright &copy; <%= link_to "Robert Wadsworth", "https://bitbucket.org/rwadsworth/", class: "text-white" %>
    </span>
  </div>
</footer>
</footer>